### ISSUE TITLE
Extraction error

### ISSUE THREAD

**Issue by dvlop** [singer-io/tap-taboola#11]
```
...
2022-10-18 08:56:01,018Z    tap -     import pytz
2022-10-18 08:56:01,018Z    tap - ModuleNotFoundError: No module named 'pytz'
2022-10-18 08:56:01,333Z target - INFO Using batch_size_prefernces of {'full_table_streams': [], 'batch_size_preference': None, 'user_batch_size_preference': None}
...
```

**Comment by frouillard** [comment]
Hi,
I got the same error this morning. Here are my logs :

> 2022-10-18 09:39:51,418Z    tap - Traceback (most recent call last):
2022-10-18 09:39:51,418Z    tap -   File "/code/orchestrator/tap-env/bin/tap-taboola", line 33, in <module>
2022-10-18 09:39:51,418Z    tap -     sys.exit(load_entry_point('tap-taboola==0.2.1', 'console_scripts', 'tap-taboola')())
2022-10-18 09:39:51,418Z    tap -   File "/code/orchestrator/tap-env/bin/tap-taboola", line 25, in importlib_load_entry_point
2022-10-18 09:39:51,418Z    tap -     return next(matches).load()
2022-10-18 09:39:51,418Z    tap -   File "/root/.pyenv/versions/3.9.6/lib/python3.9/importlib/metadata.py", line 77, in load
2022-10-18 09:39:51,418Z    tap -     module = import_module(match.group('module'))
2022-10-18 09:39:51,418Z    tap -   File "/root/.pyenv/versions/3.9.6/lib/python3.9/importlib/__init__.py", line 127, in import_module
2022-10-18 09:39:51,419Z    tap -     return _bootstrap._gcd_import(name[level:], package, level)
2022-10-18 09:39:51,419Z    tap -   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2022-10-18 09:39:51,419Z    tap -   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2022-10-18 09:39:51,419Z    tap -   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2022-10-18 09:39:51,419Z    tap -   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2022-10-18 09:39:51,419Z    tap -   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
2022-10-18 09:39:51,419Z    tap -   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2022-10-18 09:39:51,419Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/tap_taboola/__init__.py", line 16, in <module>
2022-10-18 09:39:51,419Z    tap -     import singer
2022-10-18 09:39:51,419Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/singer/__init__.py", line 1, in <module>
2022-10-18 09:39:51,419Z    tap -     from singer import utils
2022-10-18 09:39:51,419Z    tap -   File "/code/orchestrator/tap-env/lib/python3.9/site-packages/singer/utils.py", line 8, in <module>
2022-10-18 09:39:51,419Z    tap -     import pytz
2022-10-18 09:39:51,419Z    tap - ModuleNotFoundError: No module named 'pytz'
2022-10-18 09:39:51,741Z target - INFO Using batch_size_prefernces of {'full_table_streams': [], 'batch_size_preference': None, 'user_batch_size_preference': None}

Thank you for your help !
